
server:
  port: 9901
  servlet:
    context-path: /demo/

spring:
  application:
    name: demo

## 换成你自己本地的mysql配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Love1303

mybatis:
  mapper-Locations: classpath:/mapper/*.xml